### ISSUE TITLE
Logging best practices

### ISSUE THREAD

**Issue by philpott** [sublimetrix/gtm-template-ifelseif#1]
Reviewing your template I noticed that your template always logs to console due to the Logs to Console -> Always permission. 

We suggest setting the Logs to Console permission to "Only log during debug and preview".

**Comment by sublimetrix** [comment]
Thank you for your advise.
It's fixed.
Valentin Svahn.

**Comment by sublimetrix** [comment]
Hello @philpott,

I fixed the issue you report (and some other issues I found), but this template isn't already available in the GTM gallery (and also for my others "pagepath-partn" and "regexp-extract").
Do you know how many time is needed to get them availables from the gallery?
There are anothers issues in my templates?

Thank you ;)

Valentin Svahn.
