### ISSUE TITLE
"contains" is not working

### ISSUE THREAD

**Issue by DaisakuHataoka** [sublimetrix/gtm-template-ifelseif#2]
Hi, sublimetrix.

This template looks very useful and I expect it.

During testing, I found that when it was "contains", it would not work if the values were equal.
Looking at the code, the "contains" part was `0 <entry.indexOf (comp)`.
Maybe `0 <= entry.indexOf (comp)` is good?

Example: https://github.com/sublimetrix/gtm-template-ifelseif/blob/ce398ea118784e511902c9ddbfe34eddf4a8f423/template.tpl#L171

If what I pointed out is not appropriate, sorry.
Thank you for the useful templates!

**Comment by sublimetrix** [comment]
Hi @DaisakuHataoka 
Thank you for your issue report.
You're right, it was a bug and it's now fixed on the 1.2.1 version.
Thank you for your support.
Valentin Svahn.
